/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException,IOException {
        TestCases tests = new TestCases(); // Initialize your test class
        TestCase7 test7 =new TestCase7();
        TestCase8 test8=new TestCase8();

        //TODO: call your test case functions one after other here

    //test7.testCase_7();
    test8.TestCase_8();
        //tests.testcase010();

        //END Tests


        //tests.endTest(); // End your test by clearning connections and closing browser
        //test7.endTest();
        test8.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException,IOException {
        new App().getGreeting();
    }
}
