/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.awt.AWTException;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException,IOException, AWTException {
        TestCases tests = new TestCases(); // Initialize your test class
        

        //TODO: call your test case functions one after other here

    //test7.testCase_7();
    //test8.TestCase_8();
    //test9.TestCase_9();
    //test10.TestCase_10();
        //tests.testcase010();
        //test6.TestCase_6();
        tests.testCase01();

        //END Tests


        //tests.endTest(); // End your test by clearning connections and closing browser
        //test7.endTest();
        //test8.endTest();
        //test10.endTest();
        //test6.endTest();
        tests.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException,IOException, AWTException {
        new App().getGreeting();
    }
}
